version: "3"

services:
  prod:
    build:
      context: ./
      target: prod
    ports:
      - "3000:3000"
  dev:
    build:
      context: ./
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app